var GAME_LEVELS = [
  ["                                                                                ",
   "                                                              y                 ",
   "                                               yy            y                  ",
   "                                                 y        y y                   ",
   "                                                  y     y    y                  ",
   "                                                   y   y y                      ",
   "                                                     yy                         ",
   "                                                o    y  o                       ",
   "                                               xxx   y  x     s                 ",
   "                                       oo            y     o     o              ",
   "                                      xxxx           y    xxx   xxx             ",
   "                                o                    y     !x!!!x!              ",
   "                               xxx                   y      xxxxx    xx         ",
   "                        y                           y                 xx       ",
   "         ooo    y       y                            y                          ",
   "        xxxxx   y       y  xxxxx        y     y      y                          ",
   "  @     x   x   y       y  x   x o      y o o y    xxxxxxxx   o          oo     ",
   " xxxxxxxx   xxxxxx   xxxxxxx   xxxxx    xxxxxxx       oo             xxxxxxxx   ",
   "                 x   x             x    x     x    o      o      o xx           ",
   "                 x!!!x             x!!!!x     x   xxxxxxxxxxx   xxx             ",
   "                 xxxxx             xxxxxx     x!!!!!!x      x!!!!x              ",
   "                                              xxxxxxxx      xxxxxx              ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                     ooo                                                                       ",
   "                                   xxxxxxx      y                                                              ",
   "                                   xv!!!vxx  y  y  y          y       y                                        ",
   "        @                          x!!!!!x   y  y  y          y   y   y                      o                 ",
   "        x                          x!xvx!xxxxxxxxxxxxx        y   y   y                      x                 ",
   "       xxx!!                       xxx xxx           x       xxx  o  xxx                   o ! o               ",
   "      xxxxx!!                               y        xx     x     o     x                  x!!!x               ",
   "     xxxxxxx!!                        o      y yxx          x     x     x      xx        o !!!!! o             ",
   "    xxxxxxxxx!!                     o   o     y             x   oo oo   x        x       x!!!!!!!x             ",
   "   xxxxxxxxxxx!!                  xxx   xxx   y     xxxxxxxxxxxxxxxxxxxxxxx       x      !!!!!!!!!             ",
   "  xxxxxxxxxxxxx!!                             y xxxxx                     x      xx    x!!!!!!!!!!!x           ",
   " xxxxxxxxxxxxxxx!!xxx           xxx       xxxxxxx                         xx      x    !!!!!!!!!!!!!           ",
   "xxxxxxxxxxxxxxxxx!!!x o =  o xxxx     o             o    o     o                 xxxxx!!!!!!!!!!!!!!!xxx o  x  ",
   "!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx       xxx     o       = o   o        o            x                       o  x  ",
   "!!!!!!!!!!!!!!!!!!!!!!x                   xxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxx s                     o  x  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx  "],
  ["                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "                                                                                           ",
   "     oo                 o                                                                  ",
   "    xxxxxx             xxx                                                                 ",
   "         xx      =    x!!!x                                                                ",
   "          xxx        x!!!!!x                                                               ",
   " x          xx      x!!!!!!!x                                                              ",
   "            x      x!!!!!!!!!x                                                             ",
   "            x      x!!!!!!!!!x                                                             ",
   "         xxxxx    xx!!!!!!!!!x        o                y   y             xxxyy        y    ",
   "      =     x      x!!!!!!!!!x                          yy   y    y           y      y     ",
   "            x      xx!!!!!!!!!x           o                    y   y            y    y     ",
   "   s     xxxxx    xx!!!!!!!!!x        xxxxx                    y y              y  y       ",
   " o          x      x!!!!!!!!!x       xxxxxxx                   yy               yyyy       ",
   " x          x      x!!!!!!!!!x        xxxxx                    y                  yy       ",
   "            x      x!!!!!!!!!x          o                      y                   yy      ",
   "         xxxxx    xx!!!!!!!!!xx  =      o                      y                    y      ",
   " o          x      x!!!!!!!!!x       xxxxxxx                   yy               yyyy       ",
   " x          x      x!!!!!!!!!x        xxxxx                    y                  yy       ",
   "            x      x!!!!!!!!!x         | |          ooo        y                   yy      ",
   "         xxxxx    xx!!!!!!!!!xx  =                 xxxxx       y                   y       ",
   " o  =       x      x!!!!!!!!!x          o                  xxxxxxxxxxxxxx||xxxxxxxxxxxxxxxx",
   " x          x      x!!!!!!!!!x        ooooo                x !|!!!!!!!!v!  !v!!!!!!!!|!!!!x",
   "            xx     x!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              x",
   "                   x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!v!!!vx                                  x",
   "  o    o          xx!!!!!!!!!xxxxxxxxxxxxxxxxxxxx  xx  x                                  x",
   "  x    x           x!!xxxxxxxx                         x           x     oo     x         x",
   "!!!!!!!!x     x    xxvx                                x               o xx o             x",
   "xxxxxxxxxxx                          yy   oo           x      =        xxxxxx      =      x",
   "x        x       o       =            y  xxxx      o   x        o    !xxxxxxxx!    o      x",
   "x      @ x     yxx      xxxxxx      x  yyy     o    x  x        x    !xxxxxxxx!    x      x",
   "x      xxx   yyy x      x                   y   x  y   x              !xxxxxx!            x",
   "x        xxx y   x      x        o      xxxy      y    x                !xx!              x",
   "x  o     x   y   xx    ox     o   x        y    yy     x           x     vv     x         x",
   "xx       x   y  xxo     x     x     yy   yy      y     x                                  x",
   "x        x   y   x     ox o          y   y      yy            x                      x    x",
   "x       ox   y   xo    xxxxx           yyy     y                  y      oo               x",
   "x  o    xxxxxxxxxxx     x  xxxx          y     y           xxx   yyy            yy  y     x",
   "x                       x     xxx         yy  y          xxx      y               yy      x",
   "x        o o o o o o    x       xxx         y         xxx         y      oo      y        x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                           ",
   "                                                                                           "],
  ["                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "                                                                                                ",
   "             y                  y                                                               ",
   "              y                y                                                                ",
   "               y              y                      x             x                            ",
   "                y            y                        x     x     x                             ",
   "                 y          y                          x   x x   x                              ",
   "                  y        y                            x x   x x        @                      ",
   "                   y      y                              x     x     xxxxxxxxx                  ",
   "                    y    y                                               x                      ",
   "                     y  y                                                x                      ",
   "                      y                                                  x                      ",
   "                      y                                                  x                      ",
   "                      y                                              xxxxxxxxx   xx    x        ",
   "                      y                                                          x x   x        ",
   "                      y         ooooo       y     y                              x  x  x        ",
   "                      y       oo     oo     y     y                              x   x x        ",
   "                      y      o         o    y     y                              x    xx        ",
   "                      y      o         o    y     y                                             ",
   "                      y      o         o    y     y                                             ",
   "                      y      o         o    y     y                                             ",
   "                      y       oo     oo     y     y                                             ",
   "                      y         ooooo       yyyyyyy                                             ",
   "                                                                                                "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
